version: '3.3'
services:
  DB:
    restart: always
    image: postgres:14-alpine
    ports:
      - "5433:5433"
    env_file:
      - .env
    volumes:
      - postgresql:/var/lib/postgresql

volumes:
  postgresql: